In [93]:
import joblib
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

In [94]:
X = joblib.load("../models/X_full.pkl")
y = joblib.load("../models/y_class.pkl")

In [95]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [96]:
clf = LogisticRegression(max_iter=10000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [97]:
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)
print(classification_report(y_test, y_pred))

Accuracy: 0.503037667071689
              precision    recall  f1-score   support

        easy       0.53      0.35      0.42       153
        hard       0.55      0.72      0.62       389
      medium       0.38      0.28      0.33       281

    accuracy                           0.50       823
   macro avg       0.49      0.45      0.46       823
weighted avg       0.49      0.50      0.48       823



In [98]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[ 53  54  46]
 [ 24 281  84]
 [ 23 178  80]]


In [99]:
joblib.dump(clf, "../models/classifier_logreg.pkl")

['../models/classifier_logreg.pkl']